"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from cx_Freeze import setup, Executable
setup(name="dopySoft",
      version="1.1",
      description="",
      executables=[Executable("mainWindow.py")])
